<a href="https://colab.research.google.com/github/NahLima/python-para-analise-dados/blob/main/cap4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(100000)

In [4]:
my_list = list(range(100000))

Multiplicando cada sequencia por 2

In [5]:
%time for _ in range(10) : my_arr2 = my_arr * 2

CPU times: user 1.45 ms, sys: 1.68 ms, total: 3.13 ms
Wall time: 7.4 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 75.5 ms, sys: 12.7 ms, total: 88.2 ms
Wall time: 89.8 ms


**NDARRAY**

In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[-1.97374737, -2.07187876, -0.15636492],
       [-0.3389808 ,  0.7432951 ,  0.48911927]])

fazendo um calculo com os dados acima

In [12]:
multiplicando = data * 10
multiplicando

array([[-19.73747366, -20.71878755,  -1.56364917],
       [ -3.38980805,   7.43295103,   4.89119273]])

In [13]:
somando = data + data
somando

array([[-3.94749473, -4.14375751, -0.31272983],
       [-0.67796161,  1.48659021,  0.97823855]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

**CRIANDO NDARRAYS**

In [16]:
dados = [6, 7.5, 8, 0, 1]

In [18]:
dados_arr = np.array(dados)
dados_arr

array([6. , 7.5, 8. , 0. , 1. ])

sequencias aninhadas

In [21]:
dados2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
dados_arr2 = np.array(dados2)
dados_arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
dados_arr2.ndim

2

In [23]:
dados_arr2.shape

(2, 4)

**ZEROS E EMPTY**




In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[4.65032949e-310, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.94783862e-310, 1.33664410e+160]],

       [[4.46650351e-090, 5.05574680e-038],
        [1.28378502e+160, 2.04214228e+184],
        [3.99910963e+252, 1.46030983e-319]]])

**TIPOS DE DADOS**

In [31]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [32]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [29]:
arr1.dtype

dtype('float64')

In [30]:
arr2.dtype

dtype('int32')

convertendo os dados com **astype**

In [34]:
arr4 = np.array([1, 2, 3, 4, 5])
arr4.dtype

dtype('int64')

In [35]:
float_arr = arr4.astype(np.float64)
float_arr.dtype

dtype('float64')

In [36]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Indexação básica e fatiamento**

In [41]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5]

5

In [43]:
arr[5:8]

array([5, 6, 7])

In [44]:
arr[:4]

array([0, 1, 2, 3])

In [46]:
arr[7:9] = 12
arr

array([ 0,  1,  2,  3,  4,  5,  6, 12, 12,  9])

In [48]:
arr_slice = arr[7:9]
arr_slice

array([12, 12])

In [49]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5,     6,    12, 12345,
           9])

In [50]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4,  5,  6, 64, 64,  9])

In [52]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[0]

array([1, 2, 3])

In [54]:
arr2d[0][2]


3

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])