<a href="https://colab.research.google.com/github/NahLima/python-para-analise-dados/blob/main/cap4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np

In [2]:
my_arr = np.arange(100000)

In [3]:
my_list = list(range(100000))

Multiplicando cada sequencia por 2

In [ ]:
%time for _ in range(10) : my_arr2 = my_arr * 2

CPU times: user 1.45 ms, sys: 1.68 ms, total: 3.13 ms
Wall time: 7.4 ms


In [ ]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 75.5 ms, sys: 12.7 ms, total: 88.2 ms
Wall time: 89.8 ms


**NDARRAY**

In [ ]:
data = np.random.randn(2,3)

In [ ]:
data

array([[-1.97374737, -2.07187876, -0.15636492],
       [-0.3389808 ,  0.7432951 ,  0.48911927]])

fazendo um calculo com os dados acima

In [ ]:
multiplicando = data * 10
multiplicando

array([[-19.73747366, -20.71878755,  -1.56364917],
       [ -3.38980805,   7.43295103,   4.89119273]])

In [ ]:
somando = data + data
somando

array([[-3.94749473, -4.14375751, -0.31272983],
       [-0.67796161,  1.48659021,  0.97823855]])

In [ ]:
data.shape

(2, 3)

In [ ]:
data.dtype

dtype('float64')

**CRIANDO NDARRAYS**

In [ ]:
dados = [6, 7.5, 8, 0, 1]

In [ ]:
dados_arr = np.array(dados)
dados_arr

array([6. , 7.5, 8. , 0. , 1. ])

sequencias aninhadas

In [ ]:
dados2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
dados_arr2 = np.array(dados2)
dados_arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
dados_arr2.ndim

2

In [ ]:
dados_arr2.shape

(2, 4)

**ZEROS E EMPTY**




In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.empty((2,3,2))

array([[[4.65032949e-310, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.94783862e-310, 1.33664410e+160]],

       [[4.46650351e-090, 5.05574680e-038],
        [1.28378502e+160, 2.04214228e+184],
        [3.99910963e+252, 1.46030983e-319]]])

**TIPOS DE DADOS**

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [ ]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

convertendo os dados com **astype**

In [ ]:
arr4 = np.array([1, 2, 3, 4, 5])
arr4.dtype

dtype('int64')

In [ ]:
float_arr = arr4.astype(np.float64)
float_arr.dtype

dtype('float64')

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [ ]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Indexação básica e fatiamento**

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5]

5

In [6]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[:4]

array([0, 1, 2, 3])

In [ ]:
arr[7:9] = 12
arr

array([ 0,  1,  2,  3,  4,  5,  6, 12, 12,  9])

In [ ]:
arr_slice = arr[7:9]
arr_slice

array([12, 12])

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,     5,     6,    12, 12345,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4,  5,  6, 64, 64,  9])

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[0]

array([1, 2, 3])

In [12]:
arr2d[0][2]


3

In [13]:
arr2d[0, 2]

3

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) 
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [15]:
dados.shape

(2, 5)

In [16]:
dados.ndim

2

In [17]:
dados.size

10

In [18]:
dados.dtype

dtype('float64')

In [19]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [20]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

**reshape()**

In [21]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [25]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [30]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

# **indexação bolenana**

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [32]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Suponha que cada nome corresponde a uma linha do array data, primeiro vamos criar o data.

In [36]:
data = np.random.randn(7, 4)
data

array([[ 0.11045731,  0.29228162,  0.39534634, -1.377358  ],
       [-0.28268643,  0.04121618,  0.11920522, -0.06200811],
       [-0.68265492, -1.00988921, -0.08858665, -0.98069741],
       [-1.51576784, -0.93740651, -1.26263127,  0.4599415 ],
       [ 1.73680887, -0.68454215,  0.23049309,  0.92481713],
       [-0.33969344,  0.19817557,  0.32692235,  0.89268345],
       [-1.67382792,  0.58263328, -1.00054066, -2.15369117]])

In [37]:
data[names == 'Bob']

array([[ 0.11045731,  0.29228162,  0.39534634, -1.377358  ],
       [-1.51576784, -0.93740651, -1.26263127,  0.4599415 ]])

In [38]:
data[names == 'Bob',2:] # pega as ultimas duas colunas

array([[ 0.39534634, -1.377358  ],
       [-1.26263127,  0.4599415 ]])

In [39]:
data[names == 'Bob',3] #somente a ultima coluna

array([-1.377358 ,  0.4599415])

In [40]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [41]:
data[~(names == 'Bob')]  # pegando tudo menos o Bob

array([[-0.28268643,  0.04121618,  0.11920522, -0.06200811],
       [-0.68265492, -1.00988921, -0.08858665, -0.98069741],
       [ 1.73680887, -0.68454215,  0.23049309,  0.92481713],
       [-0.33969344,  0.19817557,  0.32692235,  0.89268345],
       [-1.67382792,  0.58263328, -1.00054066, -2.15369117]])

In [42]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [43]:
data[mask]

array([[ 0.11045731,  0.29228162,  0.39534634, -1.377358  ],
       [-0.68265492, -1.00988921, -0.08858665, -0.98069741],
       [-1.51576784, -0.93740651, -1.26263127,  0.4599415 ],
       [ 1.73680887, -0.68454215,  0.23049309,  0.92481713]])

**Indexação sofisticada**

In [44]:
arr = np.empty((8, 4))

In [45]:
for i in range(8):
  arr[i] = i

arr


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [46]:
arr[[4, 3, 0, 6]] # seleciona um subconjunto pré definido na ordem estipulada

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [47]:
arr[[-3, -5, -7]] # seleciona um subconjunto de baixo para cima na ordem estipulada

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

**Transposição de arrays e troca de eixos**

In [48]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
arr.T #usando o atributo especial T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [50]:
arr = np.random.randn(6, 3)
arr

array([[-0.1670496 , -1.58927798, -1.64169477],
       [ 1.90786723,  0.08757522,  0.216868  ],
       [ 0.80293954,  1.40542084,  0.93908363],
       [ 0.6152654 , -0.85879785, -0.2402305 ],
       [-0.57536682,  0.07342756,  0.56819998],
       [-0.30019139, -0.58741528,  0.02646946]])

In [51]:
np.dot(arr.T, arr)   # exemplo, quando calcular o produto da matriz interna usando np.dot

array([[5.11228819, 1.16673874, 0.95935235],
       [1.16673874, 5.59666373, 4.18039172],
       [0.95935235, 4.18039172, 4.00533403]])

In [52]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [54]:
arr.transpose((1, 0, 2))  # Nesse caso, os eixos foram reordenados com o 
                          # segundo eixo em primeiro lugar, o primeiro eixo em segundo
                          # e o último eixo permaneceu inalterado.


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

**swapaxes**


In [55]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

**Funções universais**

In [57]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.sqrt(arr) #raiz quadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [59]:
np.exp(arr) #exponencial

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [60]:
x = np.random.randn(8)
y = np.random.randn(8)

In [61]:
x

array([ 0.31027412, -2.21493259, -0.63304748,  0.64728898, -0.38315536,
        0.66890839,  0.38027516, -0.93430384])

In [62]:
y

array([-0.64435983,  0.21277559, -0.59734742,  0.66853962,  0.35690386,
       -1.86959122, -0.12514619,  1.69631841])

In [63]:
np.maximum(x, y)

array([ 0.31027412,  0.21277559, -0.59734742,  0.66853962,  0.35690386,
        0.66890839,  0.38027516,  1.69631841])

**.modf**

In [64]:
arr = np.random.randn(7) * 5
arr

array([ 1.64722971, -6.15977424,  0.37001974,  4.59713813,  3.6386341 ,
       -6.89466704,  1.96941615])

In [65]:
remainder, whole_part = np.modf(arr)

In [66]:
remainder

array([ 0.64722971, -0.15977424,  0.37001974,  0.59713813,  0.6386341 ,
       -0.89466704,  0.96941615])

In [67]:
whole_part

array([ 1., -6.,  0.,  4.,  3., -6.,  1.])

**where**

In [70]:
arr = np.random.randn(4, 4)
arr

array([[-0.08335515,  0.58542135,  1.73340059, -0.46104861],
       [-0.39978271,  0.28553191, -0.52784879,  0.32616313],
       [-0.42573466, -1.78606   , -0.87789269,  1.62322069],
       [ 0.11854336,  0.04732512,  0.76031613, -2.01686721]])

In [71]:
arr > 0

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [72]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [-2,  2, -2,  2],
       [-2, -2, -2,  2],
       [ 2,  2,  2, -2]])

In [74]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


In [82]:
# não será muito rápido para arrays grandes 
# (porque todo o trabalho está sendo feito em código Python interpretado). 
# Em segundo, ele não funcionará para arrays multidimensionais.

result = [(x if c else y) 
for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [83]:
result = np.where(cond, xarr, yarr)  #usando np.where 
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

**Métodos matemáticos e estatísticos**

In [85]:
arr = np.random.randn(5,4)
arr

array([[-0.98913764,  0.33731037,  1.37740635,  0.57563085],
       [-0.04099186,  0.34786645,  0.25721723,  0.64702316],
       [ 0.06264626,  0.91063194,  1.35767396,  0.27428436],
       [ 1.05847992, -0.52516222,  1.68620424, -1.28379729],
       [ 2.62385361,  0.06180097,  1.0155746 , -0.56616366]])

In [86]:
arr.mean()


0.45941758026840984

In [87]:
np.mean(arr)

0.45941758026840984

In [88]:
arr.sum()

9.188351605368197

In [89]:
arr.mean(axis=1)

array([0.32530248, 0.30277874, 0.65130913, 0.23393116, 0.78376638])

In [90]:
arr.sum(axis=0)

array([ 2.71485029,  1.13244751,  5.69407639, -0.35302258])

In [91]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()  

array([ 0,  1,  3,  6, 10, 15, 21, 28])

**Métodos para arrays booleanos**

In [92]:
arr = np.random.randn(100)
(arr > 0).sum() # soma os os numeros de valores positivos

59

In [93]:
bools = np.array([False, False, True, False]) 

In [94]:
bools.any()

True

In [95]:
bools.all()

False

**Ordenação**

In [96]:
arr = np.random.randn(6)
arr

array([ 0.18000156,  0.10784074, -1.83541876,  0.55856552, -0.45178498,
       -0.76897506])

In [97]:
arr.sort()

In [98]:
arr

array([-1.83541876, -0.76897506, -0.45178498,  0.10784074,  0.18000156,
        0.55856552])

**Números pseudoaleatórios**

In [100]:
samples = np.random.normal(size=(4, 4))
samples

array([[-1.9753219 ,  0.05499713,  0.58967413, -0.80899699],
       [ 2.38933936,  0.92051948, -0.47036194, -1.12442321],
       [-0.50841846,  1.34403047,  1.4681438 , -0.21407411],
       [-0.39006559,  0.84098003,  0.32743655,  0.31603835]])